spring.application.name=mini-bank-system

spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000